### ISSUE TITLE
Testing fails on Debian

### ISSUE THREAD

**Issue by ghisvail** [QuantStack/xsimd#63] opened 2017-07-11 14:45 UTC
Using version `3.0.1` + fix for select, here is the output from the tests:

```
[==========] Running 22 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 22 tests from xsimd
[ RUN      ] xsimd.sse_float_trigonometric
[       OK ] xsimd.sse_float_trigonometric (9 ms)
[ RUN      ] xsimd.sse_double_trigonometric
[       OK ] xsimd.sse_double_trigonometric (9 ms)
[ RUN      ] xsimd.sse_float_rounding
/<<PKGBUILDDIR>>/test/xsimd_rounding_test.cpp:34: Failure
Value of: res
  Actual: false
Expected: true
[  FAILED  ] xsimd.sse_float_rounding (0 ms)
[ RUN      ] xsimd.sse_double_rounding
/<<PKGBUILDDIR>>/test/xsimd_rounding_test.cpp:41: Failure
Value of: res
  Actual: false
Expected: true
[  FAILED  ] xsimd.sse_double_rounding (0 ms)
[ RUN      ] xsimd.sse_float_power
[       OK ] xsimd.sse_float_power (6 ms)
[ RUN      ] xsimd.sse_double_power
[       OK ] xsimd.sse_double_power (4 ms)
[ RUN      ] xsimd.sse_float_hyperbolic
[       OK ] xsimd.sse_float_hyperbolic (8 ms)
[ RUN      ] xsimd.sse_double_hyperbolic
[       OK ] xsimd.sse_double_hyperbolic (5 ms)
[ RUN      ] xsimd.sse_float_fp_manipulation
[       OK ] xsimd.sse_float_fp_manipulation (0 ms)
[ RUN      ] xsimd.sse_double_fp_manipulation
[       OK ] xsimd.sse_double_fp_manipulation (0 ms)
[ RUN      ] xsimd.sse_float_exponential
/<<PKGBUILDDIR>>/test/xsimd_exponential_test.cpp:35: Failure
Value of: res
  Actual: false
Expected: true
[  FAILED  ] xsimd.sse_float_exponential (10 ms)
[ RUN      ] xsimd.sse_double_exponential
/<<PKGBUILDDIR>>/test/xsimd_exponential_test.cpp:42: Failure
Value of: res
  Actual: false
Expected: true
[  FAILED  ] xsimd.sse_double_exponential (7 ms)
[ RUN      ] xsimd.sse_float_error_gamma
/<<PKGBUILDDIR>>/test/xsimd_error_gamma_test.cpp:35: Failure
Value of: res
  Actual: false
Expected: true
[  FAILED  ] xsimd.sse_float_error_gamma (23 ms)
[ RUN      ] xsimd.sse_double_error_gamma
/<<PKGBUILDDIR>>/test/xsimd_error_gamma_test.cpp:42: Failure
Value of: res
  Actual: false
Expected: true
[  FAILED  ] xsimd.sse_double_error_gamma (13 ms)
[ RUN      ] xsimd.sse_float_basic_math
[       OK ] xsimd.sse_float_basic_math (0 ms)
[ RUN      ] xsimd.sse_double_basic_math
[       OK ] xsimd.sse_double_basic_math (0 ms)
[ RUN      ] xsimd.sse_float_basic
[       OK ] xsimd.sse_float_basic (0 ms)
[ RUN      ] xsimd.sse_double_basic
[       OK ] xsimd.sse_double_basic (0 ms)
[ RUN      ] xsimd.sse_int32_basic
[       OK ] xsimd.sse_int32_basic (0 ms)
[ RUN      ] xsimd.sse_int64_basic
[       OK ] xsimd.sse_int64_basic (0 ms)
[ RUN      ] xsimd.sse_conversion
[       OK ] xsimd.sse_conversion (0 ms)
[ RUN      ] xsimd.sse_cast
[       OK ] xsimd.sse_cast (0 ms)
[----------] 22 tests from xsimd (94 ms total)

[----------] Global test environment tear-down
[==========] 22 tests from 1 test case ran. (94 ms total)
[  PASSED  ] 16 tests.
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] xsimd.sse_float_rounding
[  FAILED  ] xsimd.sse_double_rounding
[  FAILED  ] xsimd.sse_float_exponential
[  FAILED  ] xsimd.sse_double_exponential
[  FAILED  ] xsimd.sse_float_error_gamma
[  FAILED  ] xsimd.sse_double_error_gamma

 6 FAILED TESTS
```

**Comment by JohanMabille** [comment] 2017-07-11 15:18
Which version of gcc are you using ?
I will update tests so they provide more uselfull outputs.

**Comment by ghisvail** [comment] 2017-07-11 15:23
> Which version of gcc are you using ?

`6.4.0`

**Comment by ghisvail** [comment] 2017-07-13 15:59
@JohanMabille Were you able to reproduce this?

**Comment by JohanMabille** [comment] 2017-07-13 16:09
@ghisvail sorry I'm very busy with `xeus`. I don't have gcc 6 on my machines, so I hope travis will catch the error. I should have more time to deal with this problem this week end.

**Comment by JohanMabille** [comment] 2017-07-15 10:20
@ghisvail I've added gcc 6 in the matrix test, unfortunately travis uses gcc 6.2 and tests are ok with it. I've added more detailed to the console output when tests fail (on master), could you give me the output you get with GCC 6.4 ?

Also quick question, do you patch the cmake so it uses different compilation flags ? If so could you post them here ?

Last question, is it easy for you to test with gcc 6.2 ? If so can you confirm it works on your side ?
Many thanks for your help on this!

**Comment by ghisvail** [comment] 2017-07-15 11:08
I'll run a test build on debomatic and forward you the build log, which should answer most of your questions. Regarding `gcc`, I can only test with the current version on `unstable` (`6.4.0` at the moment, `7.x` soon).

**Comment by lorenzhs** [comment] 2017-09-11 08:27
Cannot reproduce on Debian unstable on master with gcc version 6.4.0 20170820 (Debian 6.4.0-4)

**Comment by JohanMabille** [comment] 2017-09-11 09:20
@lorenzhs thanks for testing!

It looks that the differences may come from a specific instruction set. I'm adding a log (both in file and console) that prints the instruction set used.

**Comment by ghisvail** [comment] 2017-09-11 09:25
I have not tried since, and things probably got moving quite a bit in testing / unstable.

**Comment by lorenzhs** [comment] 2017-09-11 11:20
I was testing on an i7-4790T (AVX2) machine, for the record.

**Comment by JohanMabille** [comment] 2018-05-28 07:30
Closing this since the problem has not been reproduced.

**Closed by JohanMabille** 2018-05-28 07:30 UTC
